export enum ConflictType {
    FIELD_CONFLICT = 'FIELD_CONFLICT',
    BLOCK_ORDER_CONFLICT = 'BLOCK_ORDER_CONFLICT',
    BLOCK_DELETED_MODIFIED = 'BLOCK_DELETED_MODIFIED',
    BLOCK_ADDED_CONFLICT = 'BLOCK_ADDED_CONFLICT',
    ACCESS_RIGHTS_CONFLICT = 'ACCESS_RIGHTS_CONFLICT',
    VERSION_CONFLICT = 'VERSION_CONFLICT'
  }