name: Angular CI

# Déclencheurs de la CI
on:
  push: # Déclenche sur un push vers ces branches
    branches:
      - main
      - dev
      - charles
  pull_request: 
    branches:
        - dev
        - main
    

# Définition des jobs
jobs:
  build:
    # Le job s'exécute sur une machine Ubuntu
    runs-on: ubuntu-22.04

    # Étapes du workflow
    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout Code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23 # Spécifie la version de Node.js
          cache: 'npm' # Active le cache pour npm

      # Étape 3 : Installer les dépendances
      - name: Install Dependencies
        run: npm i

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # Étape 5 : Exécuter les tests unitaires
      - name: Run Unit Tests
        run: |
         npm install --save-dev karma-chrome-launcher
         npm test
         

      # Étape 6 : Construire le projet pour vérifier que le build fonctionne
      - name: Build Project
        run: npm run build -- --configuration production

      # Étape 7 : Sauvegarder le rapport de couverture
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/

