name: Angular CI

on:
  push:
    branches:
      - main
      - dev
      - charles
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Linting
        run: npm run lint

      - name: Check Types
        run: npm run type-check

      - name: Start Angular App and Wait
        run: |
          npm start &
          npx wait-on http://localhost:4200 --timeout 30000

      - name: Run Unit Tests
        run: |
          mkdir -p reports/coverage
          npm test -- --coverage --output-path reports/coverage

      - name: Run E2E Tests
        run: npx cypress run --config-file=cypress.config.js

      - name: Run Lighthouse
        run: |
          mkdir -p reports/lighthouse
          lighthouse http://localhost:4200 --output json --output html --output-path reports/lighthouse/lighthouse-report.html --chrome-flags="--headless --no-sandbox --disable-gpu"

      - name: Build Project
        run: npm run build -- --configuration production

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: reports/coverage/

      - name: Upload Lighthouse Report
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: reports/lighthouse/

      - name: Upload Cypress Results
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: cypress/results/
