name: Angular CI

# Déclencheurs de la CI
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev
      - main

# Définition des jobs
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: |
           npm ci
           npm install -g lighthouse
           npm install --save-dev karma-chrome-launcher
           npm install -g wait-on

      - name: Run Linting
        run: npm run lint
      
      - name: Create environment.secret.ts
        run: |
          mkdir -p src/environments
          cat > src/environments/environment.secret.ts << EOF
          export const firebaseConfig = {
            projectId: '${{ secrets.projectId }}',
            appId: '${{ secrets.appId }}',
            storageBucket: '${{ secrets.storageBucket }}',
            apiKey: '${{ secrets.apiKey }}',
            authDomain: '${{ secrets.authDomain }}',
            messagingSenderId: '${{ secrets.messagingSenderId }}',
            measurementId: '${{ secrets.measurementId }}'
          }
          EOF

      - name: Check Types
        run: npm run type-check

      - name: Starting application for E2E Tests and Lighthouse Tests
        run: |
            npm start &
            wait-on http://localhost:4200 --timeout 30000

      - name: Run E2E Tests
        run: npm run cypress

      - name: Build Project
        run: npm run build -- --configuration production